import json

def get_emoji_for_word(jp, kr):
    kr_lower = kr.lower()
    
    # Check exact word matches first for very short or common words
    words = set(kr_lower.replace(',', '').split())
    if '문제' in words: return '❓'
    if '질문' in words: return '🙋'
    if '문' in words or '입구' in words: return '🚪'
    if '집' in words: return '🏠'
    if '방' in words: return '🚪'
    if '역' in words or '기차역' in words: return '🚉'
    if '산' in words or '등산' in words: return '⛰️'
    if '강' in words: return '🏞️'
    if '길' in words: return '🛣️'
    if '돈' in words: return '💴'
    if '옷' in words: return '👕'
    if '비' in words: return '☔'
    if '눈' in words: return '❄️'
    if '달' in words: return '🌙'
    if '병' in words and '병에' not in words: return '🤒'
    if '약' in words: return '💊'
    if '차' in words: return '🚗'

    # Fallback to general substring matching
    if '숫자' in kr_lower: return '🔢'
    if any(x in kr_lower for x in ['하나', '일일', '첫째']): return '1️⃣'
    if any(x in kr_lower for x in ['둘', '이일', '둘째']): return '2️⃣'
    if any(x in kr_lower for x in ['셋', '삼일']): return '3️⃣'
    if any(x in kr_lower for x in ['넷', '사일']): return '4️⃣'
    if any(x in kr_lower for x in ['다섯', '오일']): return '5️⃣'
    if any(x in kr_lower for x in ['여섯', '육일']): return '6️⃣'
    if any(x in kr_lower for x in ['일곱', '칠일']): return '7️⃣'
    if any(x in kr_lower for x in ['여덟', '팔일']): return '8️⃣'
    if any(x in kr_lower for x in ['아홉', '구일']): return '9️⃣'
    if any(x in kr_lower for x in ['열', '십일']): return '🔟'
    if any(x in kr_lower for x in ['백', '천', '만']): return '💯'
    
    if any(x in kr_lower for x in ['아침', '오전']): return '🌅'
    if any(x in kr_lower for x in ['밤', '저녁']): return '🌙'
    if any(x in kr_lower for x in ['점심', '오후', '낮']): return '☀️'
    if any(x in kr_lower for x in ['매일', '시간', '시계', '어제', '오늘', '내일', '올해', '내년', '작년', '년', '매주', '항상', '가끔']): return '⏰'
    
    if any(x in kr_lower for x in ['맑음', '날씨']): return '🌤️'
    if '바람' in kr_lower: return '💨'
    if '하늘' in kr_lower or '흐려지다' in kr_lower: return '☁️'
    if '정원' in kr_lower or '연못' in kr_lower: return '🌲'
    if '바다' in kr_lower: return '🌊'
    if '산' in kr_lower: return '⛰️'
    
    if '카레' in kr_lower: return '🍛'
    if any(x in kr_lower for x in ['녹차', '홍차']): return '🍵'
    if any(x in kr_lower for x in ['커피']): return '☕'
    if any(x in kr_lower for x in ['술', '맥주', '와인']): return '🍺'
    if any(x in kr_lower for x in ['음료']): return '💧'
    if any(x in kr_lower for x in ['우유']): return '🥛'
    if any(x in kr_lower for x in ['밥', '식사', '아침식사']): return '🍚'
    if any(x in kr_lower for x in ['빵']): return '🍞'
    if any(x in kr_lower for x in ['과일', '사과', '바나나', '귤']): return '🍎'
    if any(x in kr_lower for x in ['야채', '채소']): return '🥬'
    if any(x in kr_lower for x in ['고기', '돼지고기', '소고기']): return '🥩'
    if any(x in kr_lower for x in ['생선', '물고기']): return '🐟'
    if any(x in kr_lower for x in ['계란', '달걀']): return '🥚'
    if any(x in kr_lower for x in ['맛있']): return '😋'
    if any(x in kr_lower for x in ['먹다', '식당', '레스토랑']): return '🍽️'
    if '마시다' in kr_lower: return '🥤'
    if '달콤한' in kr_lower: return '🍯'
    if '맵다' in kr_lower: return '🌶️'
    if '접시' in kr_lower: return '🍽️'
    if '숟가락' in kr_lower: return '🥄'
    
    if '책' in kr_lower or '사전' in kr_lower: return '📖'
    if any(x in kr_lower for x in ['연필', '볼펜', '만년필']): return '🖊️'
    if '가방' in kr_lower: return '🎒'
    if '안경' in kr_lower: return '👓'
    if '신발' in kr_lower or '슬리퍼' in kr_lower: return '🥿'
    if '셔츠' in kr_lower: return '👕'
    if '모자' in kr_lower: return '🧢'
    if '치마' in kr_lower: return '👗'
    if '바지' in kr_lower or '주머니' in kr_lower: return '👖'
    if any(x in kr_lower for x in ['휴대폰', '전화', '스마트폰']): return '📱'
    if '컴퓨터' in kr_lower: return '💻'
    if '텔레비전' in kr_lower or 'tv' in kr_lower: return '📺'
    if '사진' in kr_lower or '카메라' in kr_lower: return '📷'
    if '지폐' in kr_lower: return '💴'
    if '지갑' in kr_lower: return '👛'
    if '우산' in kr_lower: return '☂️'
    if '편지' in kr_lower or '엽서' in kr_lower: return '✉️'
    if '신문' in kr_lower: return '📰'
    if '잡지' in kr_lower: return '📓'
    if '테이프' in kr_lower or '녹음기' in kr_lower: return '📼'
    if '포크' in kr_lower: return '🍴'
    if '젓가락' in kr_lower: return '🥢'
    if '가위' in kr_lower: return '✂️'
    if '창문' in kr_lower: return '🪟'
    if '침대' in kr_lower: return '🛏️'
    if '책상' in kr_lower or '의자' in kr_lower: return '🪑'
    if '냉장고' in kr_lower: return '🧊'
    if '전기' in kr_lower: return '⚡'
    if '엘리베이터' in kr_lower: return '🛗'
    
    if '학교' in kr_lower or '수업' in kr_lower: return '🏫'
    if '병원' in kr_lower: return '🏥'
    if '우체국' in kr_lower: return '🏣'
    if '은행' in kr_lower: return '🏦'
    if '회사' in kr_lower: return '🏢'
    if '가게' in kr_lower: return '🏪'
    if '백화점' in kr_lower: return '🏬'
    if '도서관' in kr_lower: return '🏛️'
    if '공원' in kr_lower: return '🏞️'
    if '부엌' in kr_lower: return '🍳'
    if '화장실' in kr_lower or '목욕' in kr_lower: return '🛀'
    if '거리' in kr_lower: return '🛣️'
    if '코트' in kr_lower or '스포츠' in kr_lower: return '🎾'
    if '복도' in kr_lower: return '🚶'
    
    if '자동차' in kr_lower: return '🚗'
    if '자전거' in kr_lower: return '🚲'
    if '비행기' in kr_lower: return '✈️'
    if '기차' in kr_lower or '전철' in kr_lower or '지하철' in kr_lower: return '🚆'
    if '버스' in kr_lower: return '🚌'
    if '택시' in kr_lower: return '🚕'
    if '배' in kr_lower and '타다' in kr_lower: return '🚢'
    
    if '강아지' in kr_lower: return '🐶'
    if '고양이' in kr_lower: return '🐱'
    if '꽃' in kr_lower: return '🌸'
    if '나무' in kr_lower: return '🌳'
    
    if any(x in kr_lower for x in ['사람', '인간']): return '👤'
    if any(x in kr_lower for x in ['남자', '남성']): return '👨'
    if any(x in kr_lower for x in ['여자', '여성', '아내']): return '👩'
    if any(x in kr_lower for x in ['어린이', '소년']): return '👦'
    if '선생님' in kr_lower: return '🧑‍🏫'
    if '학생' in kr_lower: return '🎓'
    if '친구' in kr_lower: return '🤝'
    if '가족' in kr_lower or '부모님' in kr_lower: return '👨‍👩‍👦'
    if any(x in kr_lower for x in ['아버지', '아빠']): return '👨'
    if any(x in kr_lower for x in ['어머니', '엄마']): return '👩'
    if '오빠' in kr_lower: return '👦'
    if '누나' in kr_lower or '언니' in kr_lower: return '👧'
    if '남동생' in kr_lower: return '👦'
    if '여동생' in kr_lower: return '👧'
    if '의사' in kr_lower: return '👨‍⚕️'
    if '경찰' in kr_lower: return '👮'
    
    if '머리' in kr_lower: return '👤'
    if '얼굴' in kr_lower: return '😊'
    if '다리' in kr_lower: return '🦵'
    if '몸' in kr_lower: return '🧍'
    if '목소리' in kr_lower: return '🗣️'
    
    if '빨강' in kr_lower or '빨간' in kr_lower: return '🔴'
    if '파랑' in kr_lower or '파란' in kr_lower: return '🔵'
    if '노랑' in kr_lower or '노란' in kr_lower: return '🟡'
    if '초록' in kr_lower or '녹색' in kr_lower: return '🟢'
    if '검정' in kr_lower or '검은' in kr_lower or '까만' in kr_lower: return '⚫'
    if '하양' in kr_lower or '하얀' in kr_lower: return '⚪'
    if '색' in kr_lower: return '🎨'
    
    if '돌아가다' in kr_lower: return '↩️'
    if '보다' in kr_lower: return '👁️'
    if '듣다' in kr_lower: return '👂'
    if '말하다' in kr_lower: return '🗣️'
    if '읽다' in kr_lower: return '📖'
    if '쓰다' in kr_lower and '글' in kr_lower: return '✍️'
    if '사다' in kr_lower: return '🛒'
    if '팔다' in kr_lower: return '💰'
    if '기다리다' in kr_lower: return '⏳'
    if '만나다' in kr_lower: return '🤝'
    if '놀다' in kr_lower: return '🎮'
    if '수영하다' in kr_lower: return '🏊'
    if '노래하다' in kr_lower: return '🎤'
    if '일하다' in kr_lower: return '💼'
    if '공부하다' in kr_lower or '연습하다' in kr_lower: return '📝'
    if '자다' in kr_lower: return '💤'
    if '일어나다' in kr_lower: return '⏰'
    if '열다' in kr_lower: return '👐'
    if '닫다' in kr_lower: return '🚪'
    if '타다' in kr_lower: return '🚆'
    if '내리다' in kr_lower: return '🚉'
    if '걷다' in kr_lower: return '🚶'
    if '달리다' in kr_lower or '뛰다' in kr_lower: return '🏃'
    if '날다' in kr_lower: return '🦅'
    if '가르치다' in kr_lower: return '👨‍🏫'
    if '배우다' in kr_lower: return '🧠'
    if '이해되다' in kr_lower: return '💡'
    if '모르다' in kr_lower: return '❓'
    if '생각하다' in kr_lower: return '🤔'
    if '만들다' in kr_lower: return '🛠️'
    if '사용하다' in kr_lower: return '🔧'
    if '당기다' in kr_lower: return '🪢'
    if '밀다' in kr_lower: return '🫸'
    if '앉다' in kr_lower: return '🪑'
    if '지우다' in kr_lower: return '🧽'
    if '닦다' in kr_lower or '씻다' in kr_lower or '청소하다' in kr_lower: return '🧹'
    if '잃다' in kr_lower: return '🔍'
    if '기억하다' in kr_lower: return '🧠'
    if '시작하다' in kr_lower: return '▶️'
    if '가다' in kr_lower or '오르다' in kr_lower or '오다' in kr_lower: return '🚶'
    
    if '크다' in kr_lower or '큰' in kr_lower: return '🐘'
    if '작다' in kr_lower or '좁은' in kr_lower: return '🐭'
    if '많다' in kr_lower: return '💯'
    if '적다' in kr_lower or '적은' in kr_lower: return '📉'
    if '좋다' in kr_lower or '좋은' in kr_lower: return '👍'
    if '나쁘다' in kr_lower or '나쁜' in kr_lower: return '👎'
    if '비싸다' in kr_lower: return '💸'
    if '싸다' in kr_lower or '싼' in kr_lower: return '🪙'
    if '덥다' in kr_lower or '뜨거운' in kr_lower: return '🥵'
    if '춥다' in kr_lower or '추운' in kr_lower: return '🥶'
    if '어렵다' in kr_lower: return '🤯'
    if '쉽다' in kr_lower: return '👌'
    if '바쁘다' in kr_lower: return '🏃'
    if '재미' in kr_lower: return '😆'
    if '무섭다' in kr_lower: return '😱'
    if '피곤' in kr_lower: return '😫'
    if '기쁘다' in kr_lower or '즐겁' in kr_lower: return '😊'
    if '슬프다' in kr_lower: return '😢'
    if '감기' in kr_lower or '아프다' in kr_lower: return '🤕'
    if '가까운' in kr_lower: return '📍'
    if '위험한' in kr_lower: return '⚠️'
    if '더러운' in kr_lower: return '💩'
    if '친절한' in kr_lower: return '🥰'
    if '서투른' in kr_lower: return '😅'
    if '예쁜' in kr_lower or '깨끗한' in kr_lower: return '✨'
    if '조용한' in kr_lower: return '🤫'
    if '걱정하다' in kr_lower: return '😟'
    if '유용한' in kr_lower or '편리한' in kr_lower: return '🛠️'
    
    if '오른쪽' in kr_lower: return '➡️'
    if '왼쪽' in kr_lower: return '⬅️'
    if '서쪽' in kr_lower: return '⬅️'
    if '동쪽' in kr_lower: return '➡️'
    if '중간' in kr_lower or '가운데' in kr_lower: return '⏺️'
    if '위' in kr_lower and len(kr_lower) < 3: return '⬆️'
    if '아래' in kr_lower and len(kr_lower) < 4: return '⬇️'
    
    if '음악' in kr_lower: return '🎵'
    if '영화' in kr_lower: return '🎬'
    if '그림' in kr_lower: return '🖼️'
    if '일본어' in kr_lower: return '🗾'
    if '영어' in kr_lower: return '🔤'
    if '나라' in kr_lower or '국가' in kr_lower: return '🌎'
    if '한국' in kr_lower: return '🇰🇷'
    
    if '사랑' in kr_lower: return '❤️'
    if '마음' in kr_lower: return '💖'
    if '꿈' in kr_lower: return '💭'
    if '이름' in kr_lower: return '📛'
    if '뉴스' in kr_lower: return '🗞️'
    if '필름' in kr_lower: return '🎞️'
    if '다르다' in kr_lower or '다른' in kr_lower: return '🔄'
    
    # Fallback to general substring mapping for some one char words that are safe enough
    if '눈' in kr_lower: return '👀'
    if '코' in kr_lower: return '👃'
    if '입' in kr_lower: return '👄'
    if '귀' in kr_lower: return '👂'
    if '손' in kr_lower: return '🖐️'
    if '발' in kr_lower: return '🦶'
    if '새' in kr_lower: return '🐦'
    if '개' in kr_lower: return '🐶'
    if '칼' in kr_lower: return '🔪'
    if '펜' in kr_lower: return '🖊️'
    if '차' in kr_lower: return '🍵'
    if '형' in kr_lower: return '👦'
    
    fallbacks = ['🔸', '🔹', '♦️', '💠', '🔘', '🟩', '🟦', '🟪', '🟨', '🟧']
    hash_val = sum(ord(c) for c in kr_lower)
    return fallbacks[hash_val % len(fallbacks)]

with open('vocab_data.js', 'r', encoding='utf-8') as f:
    text = f.read()

json_text = text.replace('const vocabData = ', '').strip()
if json_text.endswith(';'):
    json_text = json_text[:-1]

data = json.loads(json_text)

count_mapped = 0
for w in data:
    icon = get_emoji_for_word(w.get('jp', ''), w.get('kr', ''))
    if icon not in ['🔸', '🔹', '♦️', '💠', '🔘', '🟩', '🟦', '🟪', '🟨', '🟧']:
        count_mapped += 1
    w['icon'] = icon

print(f"Mapped {count_mapped} out of {len(data)} words successfully.")

with open('vocab_data.js', 'w', encoding='utf-8') as f:
    f.write('const vocabData = ' + json.dumps(data, ensure_ascii=False, indent=2) + ';\n')

print("Updated vocab_data.js with semantic emojis successfully.")
